# Site settings
title: Kyle's Blog
header-img: img/home-bg.png
email: hello.kylelee@gmail.com
copyright_name: kyleblee
description: > # this means to ignore newlines until "baseurl:"
  Short, bite-sized glimpses into my journey with code.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: wiffleballkyle
github_username:  kyleblee
learn_profile: kyleblee
email_username: hello.kylelee@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
